<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Label="Native AoT Analyzers">
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <PropertyGroup Label="Package">
        <PackageId>StrongOf.Json</PackageId>
        <IsPackable>true</IsPackable>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="readme.md" Pack="true" PackagePath=""/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\StrongOf\StrongOf.csproj" />
    </ItemGroup>
</Project>
